{{- if .Values.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  applicationInstanceLabelKey: {{ .Values.instancelabel }}
  dex:
    config: ""
    image: quay.io/ablock/dex
    openShiftOAuth: true
    version: "openshift-connector"
  ha:
    enabled: {{ .Values.ha.enabled }}
  grafana:
{{- if .Values.metrics.enabled }}  
    enabled: true
{{- else }}
    enabled: false
{{- end }}
    route: true
    size: 1
  prometheus:
{{- if .Values.metrics.enabled }}  
    enabled: true
{{- else }}
    enabled: false
{{- end }}
    route: true
    size: 1
  {{- with .Values.rbac }}
  rbac:
    {{- . | toYaml | trim | nindent 4 }}
  {{- end }}
  repositories: |
    - url: https://github.com/rht-labs/ubiquitous-journey.git
    - type: helm
      url: https://rht-labs.github.io/helm-charts
      name: rht-labs
  insecure: false
  {{- with .Values.server }}
  server:
    {{- . | toYaml | trim | nindent 4 }}
  {{- end }} 
  statusBadgeEnabled: true
  usersAnonymousEnabled: false
  version: {{ .Values.version | quote }}
{{- end }}
